#prometheus:
#  prometheusSpec:
#    additionalScrapeConfigs:
#      name: additional-scrape-configs
#      key: prometheus-additional.yaml

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
#      - job_name: 'my-custom-job'
#        static_configs:
#          - targets: ['my-service.my-namespace.svc.cluster.local:8080']

      - job_name: envoy-stats
        honor_timestamps: true
        metrics_path: /stats/prometheus
        scheme: http
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [ __meta_kubernetes_pod_container_port_name ]
            separator: ;
            regex: .*-envoy-prom
            replacement: $1
            action: keep
          - source_labels: [ __address__, __meta_kubernetes_pod_annotation_prometheus_io_port ]
            separator: ;
            regex: ([^:]+)(?::\d+)?;(\d+)
            target_label: __address__
            replacement: $1:15090
            action: replace
          - separator: ;
            regex: __meta_kubernetes_pod_label_(.+)
            replacement: $1
            action: labeldrop
          - source_labels: [ __meta_kubernetes_namespace ]
            separator: ;
            regex: (.*)
            target_label: namespace
            replacement: $1
            action: replace
          - source_labels: [ __meta_kubernetes_pod_name ]
            separator: ;
            regex: (.*)
            target_label: pod_name
            replacement: $1
            action: replace