kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-demo
  namespace: k8s-study
subjects:
  - kind: ServiceAccount
    name: sa-demo
    namespace: k8s-study
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-demo