#kind: Role
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  namespace: mynamespace
#  name: example-role
#rules:
#  - apiGroups: [""]
#    resources: ["pods"]
#    verbs: ["get", "watch", "list"]
#
#---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: k8s-study
  name: role-demo
rules:
  - verbs:
      - get
      - watch
      - list
#      - delete
    apiGroups:
      - ""
    resources:
      - pods